### ISSUE TITLE
fake useragent not found

### ISSUE THREAD

**Issue by priteshmahida** [steve-codes/selenium-web-bot#2]
what to do? i can't run selenium bot code

**Comment by priteshmahida** [comment]
Traceback (most recent call last):
  File "d:\rdd work\NAME CORRECTION DATA\selenium-web-bot-main\selenium-web-bot-main\main.py", line 9, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'

**Comment by steve-codes** [comment]
> Traceback (most recent call last):
> 
>   File "d:\rdd work\NAME CORRECTION DATA\selenium-web-bot-main\selenium-web-bot-main\main.py", line 9, in <module>
> 
>     from fake_useragent import UserAgent
> 
> ModuleNotFoundError: No module named 'fake_useragent'

Hi, did you install the required libraries from the video?

**Comment by Derandex** [comment]
I cant remember exactly how I fixed this but I think I just had to update all dependencies.
